[variables]
NODE_VERSION = "22.12.0"
NIXPACKS_NODE_VERSION = "22.12.0"

[phases.setup]
nixPkgs = ["nodejs_22", "corepack"]

[phases.install]
cmds = [
    "corepack enable",
    "corepack prepare pnpm@8.15.5 --activate",
    "pnpm install"
]

[phases.build]
cmds = ["pnpm run build"]

[phases.start]
cmd = "pnpm run start"