[phases.setup]
cmds = [
    "curl -fsSL https://deb.nodesource.com/setup_22.x | bash -",
    "apt-get install -y nodejs"
]

[phases.install]
cmds = [
    "corepack enable",
    "corepack prepare pnpm@8.15.5 --activate",
    "pnpm install"
]

[phases.build]
cmds = ["pnpm run build"]