[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.setup]
nixpkgsArchive = "51ad838b03a05b1de6f9f2a0fffecee64a9788ee"

[phases.install]
cmds = [
    "corepack enable",
    "corepack prepare pnpm@8.15.5 --activate",
    "pnpm install"
]

[phases.build]
cmds = ["pnpm run build"]
