[variables]
NODE_VERSION = "20.19.0"
NIXPACKS_NODE_VERSION = "20.19.0"

[phases.setup]
nixPkgs = ["nodejs_20", "corepack"]

[phases.install]
cmds = [
    "corepack enable",
    "corepack prepare pnpm@8.15.5 --activate",
    "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[phases.start]
cmd = "echo 'Static site built successfully'"