[variables]
NIXPACKS_NODE_VERSION = "22.16"

[phases.setup]
nixPkgs = ["corepack"]

[phases.install]
cmds = [
    "corepack enable",
    "corepack prepare pnpm@8.15.5 --activate",
    "pnpm install"
]

[phases.build]
cmds = ["pnpm run build"]