[phases.setup]
nixPkgs = ["nodejs_24", "corepack"]

[phases.install]
cmds = [
    "corepack enable",
    "corepack prepare pnpm@8.15.5 --activate",
    "pnpm install"
]

[phases.build]
cmds = ["pnpm run build"]